스프링이 아닌 Servlet이나 순수 Java를 통해 개발을 하면서 JDBC를 사용할때는 항상 SQLException이 등장한다. 하지만 스프링에서는 SQLException을 보기 힘들다. 스프링도 결국 JDBC를 활용하는데 어떻게 된 것일까? 이를 위해서는 우선 Exception과 RuntimeException에 대해 이해해야 한다.

### Exception과 RuntimeException

**Exception**

- java.lang.Exception 클래스와 그 서브클래스로 정의
- 애플리케이션 코드의 작업 중 예외상황이 발생하였을 경우 사용
- 체크예외와 언체크예외로 구분
    1. 체크예외
        - Exception의 서브클래스 & RuntimeException을 상속하지 않음
    2. 언체크예외
        - Exception의 서브클래스 & RuntimeException을 상속
- 일반적으로 예외라고 함은 체크예외를 의미한다.
- 체크예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외 처리를 하여야 한다.
- 하지 않으면 컴파일 에러 발생

**RuntimeException**

- java.lang.RuntimeException을 상속
- 명시적인 예외처리를 강제하지 않음
- 런타임 예외라고도 함
- 주로 프로그램의 오류가 있는 경우 발생
- ex) NullPointerException / IllegalArgumentException
- 코드에서 주의하면 피할 수 있음
- 굳이 예외처리를 하지 않아도 됨 (해도 상관은 없음)

## 예외 처리 방법

- 예외 복구
- 예외처리 회피
- 예외 전환

## SQLException

SQLException은 데이터 소스에 액세스하는 동안 발생하는 오류 및 경고에 대한 정보를 제공한다. JDBC API의 모든 메소드는 SQLExceptions를 예외 처리할 수 있는 것으로 선언된다. SQLException은 java.lang.Exception의 확장으로, 데이터베이스 컨텍스트에서 발생하는 실패에 관련된 추가 정보를 제공한다.

```java
public class SQLException extends java.lang.Exception
                          implements Iterable<Throwable> {
```

## DataAccessException

런타임 예외이고 DataAccessException중 가장 루트 class. 스프링에서 DB와 관련된 Exception은 모두 DataAccessException으로 감싸줘서 알려준다. DBMS에 따라 다른 에러코드를 스프링에서 일관적으로 보여준다는 장점이 있다.

```java
@SuppressWarnings("serial")
public abstract class DataAccessException extends NestedRuntimeException {

public abstract class NestedRuntimeException extends RuntimeException {
```

예외적으로 키값 중복으로 인한 예외는 데이터 엑세스 기술에 상관없이 다른 예외가 발생한다.

- JDBC → DuplicateKeyException
- 하이버네이트 → ContraintViolationException

## 스프링에서의 JDBC 예외처리

SQLException은 복구가 가능한 예외인가? 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다. 개발자가 빨리 인식할 수 있도록 발생한 예외를 빨리 전달하는 것 외에는 할 수 있는 게 없다. 스프링의 JdbcTemplate은 이 예외처리 전략을 따르고 있다. 이 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다. 따라서 JdbcTemplate을 사용하는 UserDao메소드에선 꼭 필요한 경우에만 런타임 예외인 DataAccessException을 잡아서 처리하면 되고, 그 외의 경우에는 무시해도 된다.

```java
@Override
    @Nullable
    public <T> T execute(ConnectionCallback<T> action) throws DataAccessException {
        Assert.notNull(action, "Callback object must not be null");

        Connection con = DataSourceUtils.getConnection(obtainDataSource());
        try {
            // Create close-suppressing Connection proxy, also preparing returned Statements.
            Connection conToUse = createConnectionProxy(con);
            return action.doInConnection(conToUse);
        }
        catch (SQLException ex) {
            // Release Connection early, to avoid potential connection pool deadlock
            // in the case when the exception translator hasn't been initialized yet.
            String sql = getSql(action);
            DataSourceUtils.releaseConnection(con, getDataSource());
            con = null;
            throw translateException("ConnectionCallback", sql, ex);
        }
        finally {
            DataSourceUtils.releaseConnection(con, getDataSource());
        }
    }

protected DataAccessException translateException(String task, @Nullable String sql, SQLException ex) {
        DataAccessException dae = getExceptionTranslator().translate(task, sql, ex);
        return (dae != null ? dae : new UncategorizedSQLException(task, sql, ex));
    }
```

## 질문

Java를 이용할 때는 Exception을 내지만 스프링에서 RuntimeException 으로 감싸서 처리해주는 것은 어떤 것들이 있을까?